# Generated by Django 2.2.7 on 2019-11-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statment', models.CharField(default='SOME STRING', max_length=1000)),
                ('Paragraph', models.CharField(default='SOME STRING', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRate_id', models.CharField(default='SOME STRING', max_length=100)),
                ('rates', models.CharField(default='SOME STRING', max_length=1000)),
                ('qustions', models.CharField(default='SOME STRING', max_length=1000)),
            ],
        ),
    ]
